#ifndef PINMODES_H
#define PINMODES_H

typedef enum {
	PIN_MODE_DIGITAL_IO = 0,
	PIN_MODE_CONTROLLED = 1,
	PIN_MODE_ANALOGINPUT = 2,
	PIN_MODE_SERVO = 3,
	PIN_MODE_DMA_WIGGLE = 4,
	PIN_MODE_QUADRATURE_ENC = 5,
	PIN_MODE_HYSTERESIS = 6,
	PIN_MODE_WATCHDOG = 7,
	PIN_MODE_PROTECTEDOUTPUT = 8,
	PIN_MODE_COUNTER = 9,
	PIN_MODE_DEBOUNCE = 10,
	PIN_MODE_PROPORTIONAL_OUTPUT = 11,
	PIN_MODE_LOOKUP_2D = 12,
	PIN_MODE_UART_RX = 13,
	PIN_MODE_UART_TX = 14,
	PIN_MODE_KEYPAD_SCAN_ROW = 15,
	PIN_MODE_PWM = 16,
    PIN_MODE_UART_TXRX = 17,
    PIN_MODE_PULSE_TIMER = 18,
}
pinMode_t;

#endif
